{% set name = "streamlit_passwordless" %}
{% set version = "0.13.0" %}
{% set pyproject = load_file_data('pyproject.toml') %}
{% set requires_python = pyproject.get('project', {}).get('requires-python', '') %}
{% set python_min = requires_python|replace('>=', '') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5ce10a194143004df0fff371c5a7e7fbb6cab0745016bf7b4d4e14a7d1b50877

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - stp = streamlit_passwordless.cli.main:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=62.0
  run:
    - python >={{ python_min }}
    - click >=8.0
    # Running the streamlit_passwordless custom component does not work with Streamlit v1.34 using conda.
    - streamlit >=1.24,!=1.34
    - passwordless >=0.1
    - pydantic >=2.0
    - sqlalchemy >=2.0

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - streamlit_passwordless
  commands:
    - pip check

about:
  home: https://github.com/antonlydell/streamlit-passwordless
  summary: 'A user model for Streamlit applications based on passwordless technology.'
  description: |
    Streamlit Passwordless provides a user model for Streamlit applications, which allows
    users to securely authenticate with a Streamlit application using passkeys. It integrates
    with Bitwarden Passwordless.dev for the passkey management.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://passwordless.streamlit.app
  dev_url: https://github.com/antonlydell/streamlit-passwordless

extra:
  recipe-maintainers:
    - antonlydell
