{% set name = "streamlit_passwordless" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8eee8376c33aaab97adf1b7d6966a43bdcfc596dffd6eaade83132881d0d729a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.11
    - pip
    - setuptools >=62.0
  run:
    - python >=3.11
    # Running the streamlit_passwordless custom component does not work with Streamlit v1.34 using conda.
    - streamlit >=1.24,!=1.34
    - passwordless >=0.1
    - pydantic >=2.0
    - sqlalchemy >=2.0

test:
  requires:
    - pip
  imports:
    - streamlit_passwordless
  commands:
    - pip check

about:
  home: https://github.com/antonlydell/streamlit-passwordless
  summary: 'A user model for Streamlit applications based on passwordless technology.'
  description: |
    streamlit-passwordless provides a user model for Streamlit applications based on the
    Bitwarden passwordless technology. It allows users to securely authenticate with a
    Streamlit application using the passkey FIDO2 and WebAuthn protocols.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://passwordless.streamlit.app
  dev_url: https://github.com/antonlydell/streamlit-passwordless

extra:
  recipe-maintainers:
    - antonlydell
